apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: lrxs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lrxs
    app.kubernetes.io/part-of: byoc-app-qbve
  name: lrxsitw2
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: lrxs
    weight: null
status: {}
