apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: lrxs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lrxs
    app.kubernetes.io/part-of: byoc-app-qbve
  name: lrxs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: lrxs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: lrxs
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-ncqs-tenant/byoc-app-qbve/lrxs@sha256:60c82d71042c1578fb2255d1cfc910a22ff2b32eafe6bcda2846552c314b8b84
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
